codenvy/che-core

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/ProjectStateHandler.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/problemDialog/ProjectProblemDialog.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/problemDialog/ProjectProblemDialog.ui.xml
ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties

IDEX-2013. Fix project configuration proposal pop up.

IDEX-2013. Fix project configuration proposal pop up.

---

ide/che-core-ide-api/pom.xml
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/action/DefaultActionGroup.java
ide/che-core-ide-api/src/test/java/org/eclipse/che/ide/api/action/DefaultActionGroupTest.java

Created new sorting algorythm for action groups, that will correctly handle "BEFORE" and "AFTER" constraints

IDEX-2188 Fixed actions sorting algorythm and added tests

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/ProjectStateHandler.java

IDEX-2332. Fixed: Wrong behavior the 'Project configuration'.

IDEX-2332. Fixed: Wrong behavior the 'Project configuration'.

---

platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectService.java

IDEX-2172. Fixed: The empty project is not deleted.

IDEX-2172. Fixed: The empty project is not deleted.

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projecttype/wizard/runnerspage/RunnersPagePresenter.java

IDEX-2320. Set default memory size at configure project from wizard.

IDEX-2320. Set default memory size at configure project from wizard.

---

platform-api-client-gwt/che-core-client-gwt-account/src/main/java/org/eclipse/che/api/account/gwt/client/AccountServiceClient.java
platform-api-client-gwt/che-core-client-gwt-account/src/main/java/org/eclipse/che/api/account/gwt/client/AccountServiceClientImpl.java

@vparfonov : IDEX-2286: add redistribute resources method to Account service

IDEX-2286: add redistribute resources method

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/CoreLocalizationConstant.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/client/BootstrapController.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/ProjectStateHandler.java
ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties

IDEX-2127. When running che on desktop, change the browser tab title.

IDEX-2127. When running che on desktop, change the browser tab title.

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/ProjectStateHandler.java

IDEX-2411: Fixed bug related to showing project in project tree after import

---

commons/che-core-commons-gwt/src/main/java/org/eclipse/che/api/promises/client/Promise.java
commons/che-core-commons-gwt/src/main/java/org/eclipse/che/api/promises/client/PromiseError.java
commons/che-core-commons-gwt/src/main/java/org/eclipse/che/api/promises/client/js/JsPromise.java
commons/che-core-commons-gwt/src/main/java/org/eclipse/che/api/promises/client/js/JsPromiseError.java

Better promises chaining
Useful promise errors

Promises update

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projecttype/wizard/presenter/ProjectWizardPresenter.java

IDEX-2437. Init wizard page when ProjectWizard received from cache.

IDEX-2437. Init wizard page when ProjectWizard received from cache.

---

platform-api/che-core-api-runner/src/main/java/org/eclipse/che/api/runner/RunQueue.java
platform-api/che-core-api-runner/src/main/java/org/eclipse/che/api/runner/RunQueueTask.java

@skabashnyuk Can you take a look?

CLDIDE-2351 Added resetting of interrupted flag

---

platform-api/che-core-api-runner/src/main/java/org/eclipse/che/api/runner/RunnerService.java

IDEX-2422: run processes, started with API, are displayed in dashboard

---

ide/che-core-ide-api/src/main/resources/org/eclipse/che/ide/api/ui/style.css

IDEX-1160: Deleted unused css styles

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/parts/PartStackUIResources.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/parts/base/BaseView.java
ide/che-core-ide-api/src/main/resources/org/eclipse/che/ide/api/parts/partstack.css

IDEX-2367: Added horizontal splitter and menu to change panel state

---

platform-api/che-core-api-runner/src/main/java/org/eclipse/che/api/runner/RunQueue.java
platform-api/che-core-api-runner/src/main/java/org/eclipse/che/api/runner/RunQueueTask.java
platform-api/che-core-api-runner/src/main/java/org/eclipse/che/api/runner/dto/ApplicationProcessDescriptor.java

IDEX-2450: Fixed bug related to wrong information about scope

---

platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/shared/EnvironmentId.java
platform-api/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/EnvironmentIdTest.java
platform-api/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/ProjectServiceTest.java

IDEX-2521: fixed path of the project environments

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/project/tree/generic/ProjectNode.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/RenameItemAction.java

IDEX-2214: Fixed wrong behaviour during maven module renaming

---

platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/shared/EnvironmentId.java
platform-api/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/EnvironmentIdTest.java

IDEX-2534: Fixed bug related to launching project scope machine

---

commons/che-core-commons-gwt/src/main/java/org/eclipse/che/ide/ui/tree/Tree.java

Fixed problem with selection parent node by left arrow key

IDEX-1936: Fixed problem with selection parent node by left arrow key

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/client/BootstrapController.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/statepersistance/AppStateManager.java

Fixed json appState for last project path. Clean up BootstrapController

Fixed json appState for last project path. Clean up BootstrapController

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/client/AnalyticsSessions.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/client/BootstrapController.java

This is pull request for issue https://jira.codenvycorp.com/browse/DASHB-660

DASHB-660 : Generation SESSION-ID for analytics changed.

---

commons/che-core-commons-inject/src/main/java/org/eclipse/che/inject/Matchers.java
pom.xml

Release 3.9.5

---

platform-api/che-core-api-runner/src/main/java/org/eclipse/che/api/runner/internal/Runner.java

Release 3.9.6

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/client/StyleInjector.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/dropdown/DropDownHeaderWidgetImpl.java

IDEX-2568: improved list of runners into toolbar

---

platform-api/che-core-api-account/src/main/java/org/eclipse/che/api/account/server/AccountService.java
platform-api/che-core-api-account/src/main/java/org/eclipse/che/api/account/server/dao/AccountDao.java

Added Beta annotations to subscription API

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/client/BootstrapController.java

IDEX-2457: added the browser dialog box with error message

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/statepersistance/ActiveNodePersistentComponent.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/statepersistance/OpenedNodesPersistenceComponent.java

Fixed using concrete realization instead interfaceProjectExplorerView

Fixed using concrete realization instead interfaceProjectExplorerView

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/PartStackPresenter.java
platform-api-client-gwt/che-core-client-gwt-machine/src/main/java/org/eclipse/che/api/machine/gwt/client/MachineServiceClient.java
platform-api-client-gwt/che-core-client-gwt-machine/src/main/java/org/eclipse/che/api/machine/gwt/client/MachineServiceClientImpl.java

IDEX-2578: Developed machine perspective view.

---

platform-api/che-core-api-vfs/src/test/java/org/eclipse/che/api/vfs/server/impl/memory/SearcherTest.java

Hi,
Following my previous pull request #77, I added tests for Lucene Searcher that test: 
1. contains query 
2. query as a regular expression 
3. query that contains special characters
Thanks,
Rima

Added tests for Lucene Searcher

---

platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/Project.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectService.java
platform-api/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/ProjectServiceTest.java

Fixed renaming just created maven modules

IDEX-2606 Fixed renaming just created maven modules.

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/event/ProjectDescriptorChangedEvent.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/event/ProjectDescriptorChangedHandler.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/project/tree/generic/GenericTreeStructure.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/project/tree/generic/ModuleNode.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/project/tree/generic/NodeFactory.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/project/tree/generic/ProjectNode.java
ide/che-core-ide-api/src/test/java/org/eclipse/che/ide/api/project/tree/generic/ProjectNodeTest.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/DtoConverter.java

IDEX-2607: Set the context to the current module (not only top level project)

---

platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/Project.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectService.java
platform-api/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/ProjectTest.java

Fixed problem when we rename module inside module

IDEX-2606: Fixed problem when we rename module inside module

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/ProjectStateHandler.java

Remove unnecessary RefreshProjectTreeEvent when open problem project.

IDEX-2642. Remove unnecessary RefreshProjectTreeEvent when open problem project.

---

platform-api/che-core-api-builder/src/main/java/org/eclipse/che/api/builder/BuildQueue.java
platform-api/che-core-api-runner/src/main/java/org/eclipse/che/api/runner/RunQueue.java
platform-api/che-core-api-runner/src/test/java/org/eclipse/che/api/runner/RunQueueTest.java

IDEX-1038: removed unusable properties

---

platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/BadRequestException.java
platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/ApiExceptionMapper.java

@skabashnyuk Can you merge these changes?

Added BadRequestException

---

ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/events/DocumentChangeEvent.java

Hello,
I need this improvement for real time live editing plugin
This comes with https://github.com/codenvy/che-plugins/pull/148
Thanks,

Demo flux: adding removed char count to document change event

---

che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/CommandProcess.java
che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/NativeGitConnection.java
che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/commands/RemoteUpdateCommand.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/FetchTest.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/PullTest.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/PushTest.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/RemoteAddTest.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/RemoteListTest.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/RemoteUpdateTest.java

Fixed git impl native tests

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/ProjectStateHandler.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/problemDialog/ProjectProblemDialog.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/problemDialog/ProjectProblemDialog.ui.xml
ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties

Added ability to configure project as blank without wizard.

IDEX-2774. Added ability to configure project as blank without wizard.

---

platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitProjectImporter.java

@vparfonov Can you review these changes?

IDEX-2900 Fixed behavior of keep directory feature

---

README.md

Update readme file that JDK 1.8 is required (and not 1.7)

Update readme with JDK minimal version to 1.8

---

commons/che-core-commons-lang/src/main/java/org/eclipse/che/commons/lang/ZipUtils.java

Change-Id: Ia637d77e1b29f4b606bb3b7c4fdbee8577e0a4ff

Allow passing general streams to ZipUtils.zipFiles()

---

platform-api/che-core-api-builder/src/main/java/org/eclipse/che/api/builder/BuildQueueTask.java

Change-Id: Icf9cf5db9b6cdc768a55c7fd31e123458833a6a7

Bug fix: populate workspace and project fields of BuildTaskDescriptor

---

che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/NativeGitConnection.java
che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/commands/BranchCheckoutCommand.java
platform-api-client-gwt/che-core-client-gwt-git/src/main/java/org/eclipse/che/api/git/gwt/client/GitServiceClient.java
platform-api-client-gwt/che-core-client-gwt-git/src/main/java/org/eclipse/che/api/git/gwt/client/GitServiceClientImpl.java
platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/shared/BranchCheckoutRequest.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/BranchCheckoutTest.java

@skabashnyuk  Can you review these changes?

IDEX-2440 Added possibility to manually setting of tracked branch

---

che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/ssh/GitSshScript.java

@skabashnyuk Can you review these changes?

IDEX-2933 Added setting of IdentitiesOnly option in ssh script template

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/theme/Style.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/theme/Theme.java
ide/che-core-ide-api/src/main/resources/org/eclipse/che/ide/api/ui/style.css
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/DarkTheme.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/LightTheme.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/toolbar/ActionButton.java
ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/radiobuttongroup/radio-button-group.css

IDEX-2869: Refactoring styles of toolbar switcher

---

commons/che-core-commons-gwt/src/main/java/org/eclipse/che/ide/ui/loaders/initializationLoader/LoaderViewImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/bootstrap/WorkspaceComponent.java

Don't unsubscribe from channel before MachineStatusNotifier gets machine status. 
Fixed NullPointerException.

IDEX-2992. Don't unsubscribe from channel before MachineStatusNotifier gets machine status. Fixed NullPointerException.

---

che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/GitAskPassScript.java
che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/NativeGit.java
che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/NativeGitConnection.java
che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/NativeGitConnectionFactory.java
che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/commands/BranchDeleteCommand.java
che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/commands/BranchRenameCommand.java
che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/commands/CloneCommand.java
che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/commands/FetchCommand.java
che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/commands/LsRemoteCommand.java
che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/commands/PullCommand.java
che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/commands/PushCommand.java
che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/commands/RemoteOperationCommand.java
che-core-git-impl-native/src/test/java/org/eclipse/che/git/impl/GitConnectionFactoryProvider.java
platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/CredentialsLoader.java
platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/CredentialsProvider.java
platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitConnection.java
platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitConnectionFactory.java
platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/UserCredential.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/FetchTest.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/GetCommitersTest.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/GitTestUtil.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/MergeTest.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/PullTest.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/PushTest.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/RemoteAddTest.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/RemoteListTest.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/ResetTest.java

IDEX-2180: get gitUser information from preferences

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/project/node/HasStorablePath.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/CreateModuleAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/editor/EditorAgentImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/newresource/AbstractNewResourceAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/newresource/NewFolderAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/NewProjectExplorerPresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/NewProjectExplorerView.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/NewProjectExplorerViewImpl.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/smartTree/GoIntoMode.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/smartTree/LoadParams.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/smartTree/Tree.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/smartTree/TreeNodeLoader.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/smartTree/event/LoadEvent.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectService.java

IDEX-2971: Tree collapse fixes

---

ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/smartTree/TreeSelectionModel.java

IDEX-3004: add ability to handle enter key for the tree

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/action/IdeActions.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/theme/Style.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/theme/Theme.java
ide/che-core-ide-api/src/main/resources/org/eclipse/che/ide/api/ui/style.css
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/ActionManagerImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/StandardComponentInitializer.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/DarkTheme.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/LightTheme.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/dropdown/DropDownHeaderWidget.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/dropdown/DropDownHeaderWidgetImpl.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/dropdown/DropDownHeaderWidgetImpl.ui.xml
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/dropdown/DropDownListMenu.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/dropdown/SimpleListElementAction.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/toolbar/ToolbarPresenter.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/toolbar/ToolbarResources.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/toolbar/ToolbarView.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/toolbar/ToolbarViewImpl.java
ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/dropdown/DropdownList.css
ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/dropdown/expansionIcon.svg
ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/radiobuttongroup/radio-button-group.css
ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/toolbar/popup-menu.css
ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/toolbar/toolbar.css
ide/che-core-ide-ui/src/test/java/org/eclipse/che/ide/ui/dropdown/SimpleListElementActionTest.java

IDEX-2868: Change styles for the command bar

---

ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties

Changed "IDE Settings" to "IDE" in IDE prefs window, and updated "Plug-ins Configuration" to "Plug-Ins".

Update IDE preferences text

---

platform-api/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/UserProfileService.java

See https://github.com/codenvy/che-core/pull/220

Bug fix: synchronize preferences update

---

platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/MachineConfigImpl.java
platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/RuntimeWorkspaceImpl.java
platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/UsersWorkspaceImpl.java

@garagatyi, @skabashnyuk please review

Cldide 2541

---

commons/che-core-commons-gwt/src/main/java/org/eclipse/che/ide/rest/AsyncRequestCallback.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/editor/EditorAgent.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/Resources.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/client/StyleInjector.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/editor/EditorAgentImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/PartStackPresenter.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/cellview/CellTreeResources.java
ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/cellview/cellTree.css

IDEX-3017: improved move refactoring wizard

---

platform-api/che-core-api-dto/src/main/java/org/eclipse/che/dto/generator/DtoImplClientTemplate.java
platform-api/che-core-api-dto/src/main/java/org/eclipse/che/dto/generator/DtoImplServerTemplate.java
platform-api/che-core-api-dto/src/test/java/org/eclipse/che/dto/ServerDtoTest.java
platform-api/che-core-api-dto/src/test/java/org/eclipse/che/dto/definitions/DtoWithAny.java

Fixed generating of sources code for List of Object

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/Constants.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projecttype/wizard/presenter/ProjectWizardPresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projecttype/wizard/presenter/ProjectWizardView.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projecttype/wizard/presenter/ProjectWizardViewImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projecttype/wizard/presenter/ProjectWizardViewImpl.ui.xml

Remove 'Builder Env Configuration and Runner Env Configuration' section in project wizard.

IDEX-3138. Remove 'Builder Env Configuration and Runner Env Configuration' section.

---

che-core-vfs-impl/src/main/java/org/eclipse/che/vfs/impl/fs/FSMountPoint.java
platform-api/che-core-api-vfs/src/main/java/org/eclipse/che/api/vfs/server/impl/memory/MemoryVirtualFile.java

CLDIDE-2537 Disable vfs permission checking. It will be removed from API server. On machines it will be checked on other lavel
Signed-off-by: Sergii Kabashniuk <skabashnyuk@codenvy.com>

CLDIDE-2537 Disable vfs permission checking

---

commons/che-core-commons-gwt/src/main/java/org/eclipse/che/ide/rest/AsyncRequest.java

Fix NPE in AsyncRequestCallback.

IDEX-3054. Fix NPE in AsyncRequestCallback.

---

platform-api/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticationService.java
platform-api/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticator.java

Add method for retrieving OAuth token
Fix NPE in OAuthAuthenticator
Add RolesAllowed annotation to invalidate method
Reformat the code

Fix API methods for working with oauth2 token

---

platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/DefaultProjectManager.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/handlers/ProjectHandlerRegistry.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/handlers/RemoveModuleHandler.java

Remove module by absolute and relative path on server side.

IDEX-2899. Remove module by absolute and relative path on server side.

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/client/BootstrapController.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/debug/BreakpointManager.java
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/debug/BreakpointManagerImpl.java
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/debug/BreakpointRendererImpl.java
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/events/GutterClickEvent.java
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/gutter/Gutter.java

Orion can set breakpoints marks

IDEX-3134: Port setting breakpoints

---

commons/che-core-maven-plugin/pom.xml
commons/che-core-maven-plugin/src/main/java/org/eclipse/che/maven/plugin/CheMojo.java
commons/che-core-maven-plugin/src/main/resources/META-INF/plexus/components.xml
commons/che-core-maven-plugin/src/test/java/org/eclipse/che/maven/plugin/CheMojoTest.java
commons/che-core-maven-plugin/src/test/java/org/eclipse/che/maven/plugin/stub/CheMojoProjectStub.java
commons/che-core-maven-plugin/src/test/java/org/eclipse/che/maven/plugin/stub/CheMojoProjectStubAssembly1.java
commons/che-core-maven-plugin/src/test/java/org/eclipse/che/maven/plugin/stub/CheMojoProjectStubAssembly2.java
commons/che-core-maven-plugin/src/test/java/org/eclipse/che/maven/plugin/stub/CheMojoProjectStubSingle.java
commons/che-core-maven-plugin/src/test/projects/assembly1/pom.xml
commons/che-core-maven-plugin/src/test/projects/assembly1/src/main/che/machines/machine1/Dockerfile
commons/che-core-maven-plugin/src/test/projects/assembly2/pom.xml
commons/che-core-maven-plugin/src/test/projects/single/pom.xml
commons/che-core-maven-plugin/src/test/projects/single/src/main/che/machines/machine1/Dockerfile
commons/che-core-maven-plugin/src/test/projects/single/src/main/java/org/eclipse/che/maven/plugin/test/Hello.java
commons/che-core-maven-plugin/src/test/projects/single/src/main/resources/org/eclipse/che/maven/plugin/test/README
commons/pom.xml

Change-Id: Icb9e4fe5453200e085b41af4ad56f0e468132368

IDEX-3240 Move from che/ repository the maven plugin

---

ide/che-core-ide-app/pom.xml
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/inject/CoreGinModule.java
platform-api-client-gwt/che-core-client-gwt-auth/src/main/java/org/eclipse/che/api/auth/client/OAuthServiceClient.java
platform-api-client-gwt/che-core-client-gwt-auth/src/main/java/org/eclipse/che/api/auth/client/OAuthServiceClientImpl.java
platform-api-client-gwt/che-core-client-gwt-auth/src/main/resources/org/eclipse/che/api/Auth.gwt.xml
platform-api/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticator.java
platform-api/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/RemoteOAuthTokenProvider.java

Fixed bugs critical for openshift

---

platform-api/che-core-api-runner/src/main/java/org/eclipse/che/api/runner/RunnerService.java
platform-api/che-core-api-runner/src/test/java/org/eclipse/che/api/runner/RunnerServiceTest.java

Add account query parameter to getAllRunningProcesses API method.
It is needed to get all running processes that related to account.
For now if we get all running processes we will see processes that related to current user, but if there is a run process started from temporary workspace we will not see it.

IDEX-3300: Add check that workspace belongs to account owner

---

ide/che-core-ide-api/pom.xml

Change-Id: Idc9feddf5b501bc1fa458925563ee991155f9cbe

Remove duplicated dependency

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/bootstrap/WorkspaceComponent.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/statepersistance/AppStateManager.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/statepersistance/dto/AppState.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/workspace/create/CreateWorkspacePresenterTest.java

IDEX-3238: Fix start recent workspace

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/CoreLocalizationConstant.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/bootstrap/WorkspaceComponent.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/create/CreateWorkspacePresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/start/StartWorkspacePresenter.java
ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/workspace/create/CreateWorkspacePresenterTest.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/workspace/start/StartWorkspacePresenterTest.java

IDEX-3229: Fix frequent changing DOM model, during machine output

---

platform-api/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticator.java

Fix refreshing of token on its expiration

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/ProjectExplorerPresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/ProjectExplorerView.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/ProjectExplorerViewImpl.java

IDEX-3225: add an ability to remove Node from the project tree

---

commons/che-core-commons-gwt/src/main/java/org/eclipse/che/ide/commons/exception/UnauthorizedException.java

Add setting of message in UnauthorizedException

---

platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/HttpJsonHelper.java

1. Removed user authorization token from url. For the cases when some component decided to put ulr in log file. This way we will remove possibility of token leaks.
2. We drop a hint to server that we expect application-json response. this needed if server have two method with different produces content type for same path.

Cldide 2597 HttpJsonHelper improvements

---

platform-api/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/FactoryService.java

It is needed to send request to proper vcs service.

IDEX-2470: Add checking of svn project type

---

platform-api-client-gwt/che-core-client-gwt-auth/src/main/java/org/eclipse/che/api/auth/client/OAuthServiceClient.java
platform-api-client-gwt/che-core-client-gwt-auth/src/main/java/org/eclipse/che/api/auth/client/OAuthServiceClientImpl.java

Fix type of token in getToken method

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/ProjectExplorerPresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/ProjectExplorerViewImpl.java

Reset Go Into mode when new project created and when we try to scroll to file that is outside Go Into node

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/theme/Style.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/theme/Theme.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/DarkTheme.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/LightTheme.java
ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/smartTree/TreeStyles.css

IDEX-3430: Adapt Project Tree for light theme

---

platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitProjectImporter.java

IDEX-3394: Make it possible to setup git branch and use correct sparse checkout

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/upload/file/UploadFilePresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/upload/folder/UploadFolderFromZipPresenter.java

IIU-219: Upload File feature doesn't work

---

che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/NativeGitConnection.java
ide/che-core-ide-app/pom.xml
platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitConnection.java
platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitValueProviderFactory.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/IsInsideWorkTreeTest.java
platform-api/che-core-api-user/pom.xml

IDEX-3508: improve verification if dir belongs to git

---

platform-api-client-gwt/che-core-client-gwt-vfs/src/main/java/org/eclipse/che/api/vfs/gwt/client/VfsServiceClientImpl.java

IDE making vfs calls to api but it have to make call to ext server
@vparfonov @skabashnyuk

IDEX-3330: Make vfs call to ext server when importing a project

---

platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/HttpJsonHelper.java
platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitProjectImporter.java

This is pull request for issue https://jira.codenvycorp.com/browse/CLDIDE-2627

CLDIDE-2627 : Replace some messages with more generic in HttpJsonHelper and GitProjectImporter

---

platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitProjectImporter.java

This is pull request for issue https://jira.codenvycorp.com/browse/CLDIDE-2627

CLDIDE-2627 : Replace message with more generic in GitProjectImporter

---

commons/che-core-commons-gwt/src/main/java/org/eclipse/che/ide/mvp/View.java
commons/che-core-commons-gwt/src/main/java/org/eclipse/che/ide/util/input/KeyCodeMap.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/CoreLocalizationConstant.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/DeleteItemAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/HotKeysListAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/SwitchLeftTabAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/SwitchRightTabAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/StandardComponentInitializer.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/inject/CoreGinModule.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/hotkeys/HasHotKeyItems.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/hotkeys/HotKeyItem.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/hotkeys/dialog/HotKeysDialogPresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/hotkeys/dialog/HotKeysDialogView.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/hotkeys/dialog/HotKeysDialogViewImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/hotkeys/dialog/HotKeysDialogViewImpl.ui.xml
ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/texteditor/EditorWidget.java
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/texteditor/EmbeddedTextEditorPresenter.java
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/texteditor/TemporaryKeybindingsManager.java
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/texteditor/TextEditorInit.java
ide/che-core-ide-jseditor/src/main/resources/org/eclipse/che/ide/jseditor/JsEditor.gwt.xml

Show all Hotkey that available in Che (including keys for Orion)

IDEX-3284: Show all Hotkey that available in Che

---

platform-api/che-core-api-infrastructure-local/pom.xml
platform-api/che-core-api-infrastructure-local/src/main/java/org/eclipse/che/api/local/LocalInfrastructureModule.java
platform-api/che-core-api-infrastructure-local/src/main/java/org/eclipse/che/api/local/LocalWorkspaceDaoImpl.java
platform-api/che-core-api-infrastructure-local/src/main/java/org/eclipse/che/api/local/ModuleConfigAdapter.java

@evoevodin @vparfonov @garagatyi @skabashnyuk please review

IDEX-3590: Fix bug related to launch Che after stopping

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/ActionManagerImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/ExpandNodeAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/OpenFileAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/PasteAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/find/FindActionPresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/client/DtoRegistrar.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/client/ExtensionInitializer.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/menu/MenuBarItem.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/newresource/AbstractNewResourceAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/notification/NotificationItem.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/ProjectExplorerViewImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/preferences/PreferencesViewImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/project/node/remove/DeleteNodeHandler.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/wizard/mainpage/MainPageViewImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projecttype/wizard/categoriespage/CategoriesPageViewImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/settings/SettingsViewImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/settings/common/AbstractSettingsPagePresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/start/StartWorkspaceEvent.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/start/StopWorkspaceEvent.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/notification/NotificationManagerImplTest.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/workspace/perspectives/general/AbstractPerspectiveTest.java

Fix FindBugs issues

---

che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/NativeGitConnection.java
che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/commands/CloneCommand.java
platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitProjectImporter.java
platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/shared/CloneRequest.java

We need git clone wirh --recursive to clone multi-module project with submodules.
Will be merged only in 3.x
@vparfonov @skabashnyuk

IDEX-2981: Add '--recursive' parameter to git clone command

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/wizard/ImportProjectNotificationSubscriberImpl.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectService.java

Fix import project

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/project/type/wizard/ProjectWizardMode.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/DownloadItemAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/ProjectImporterResource.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/local/LocalZipImporterPagePresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/local/LocalZipImporterPageView.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/local/LocalZipImporterPageViewImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/local/LocalZipImporterPageViewImpl.ui.xml
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/zip/ZipImporterPagePresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/zip/ZipImporterPageView.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/zip/ZipImporterPageViewImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/zip/ZipImporterPageViewImpl.ui.xml
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projecttype/wizard/categoriespage/CategoriesPagePresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projecttype/wizard/categoriespage/CategoriesPageView.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projecttype/wizard/categoriespage/CategoriesPageViewImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projecttype/wizard/categoriespage/CategoriesPageViewImpl.ui.xml
ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/Core.css
ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/projectimport/ImporterPage.css
ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/projecttype/wizard/categoriespage/MainPage.css
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/projectimport/local/LocalZipImporterPagePresenterTest.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/projectimport/zip/ZipImporterPagePresenterTest.java

IDEX-3452: Remove public/private visibility switcher from project creation/importing wizard

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/imageviewer/ImageViewer.java

We can't open images, because inherited method getView() throws Unsupported Exception.

IDEX-3465: Fix opening images

---

platform-api-client-gwt/che-core-client-gwt-machine/src/main/java/org/eclipse/che/api/machine/gwt/client/MachineServiceClient.java
platform-api-client-gwt/che-core-client-gwt-machine/src/main/java/org/eclipse/che/api/machine/gwt/client/MachineServiceClientImpl.java

Add getFileContent() method to MachineServiceClient

IDEX-3011. Add ability show log from extension server.

---

che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/NativeGitConnection.java
platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitConnection.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/IsInsideWorkTreeTest.java

@sleshchenko: please review changes.

IDEX-3657: isInsideWorkTree should return false if directory is outside repo

---

commons/che-core-commons-gwt/src/main/java/org/eclipse/che/api/promises/client/Function.java
commons/che-core-commons-gwt/src/main/java/org/eclipse/che/api/promises/client/Operation.java
commons/che-core-commons-gwt/src/main/java/org/eclipse/che/api/promises/client/Promise.java
commons/che-core-commons-gwt/src/main/java/org/eclipse/che/api/promises/client/PromiseError.java
commons/che-core-commons-gwt/src/main/java/org/eclipse/che/api/promises/client/Thenable.java
commons/che-core-commons-gwt/src/main/java/org/eclipse/che/api/promises/client/callback/AsyncPromiseHelper.java
commons/che-core-commons-gwt/src/main/java/org/eclipse/che/api/promises/client/callback/CallbackPromiseHelper.java
commons/che-core-commons-gwt/src/main/java/org/eclipse/che/api/promises/client/callback/PromiseHelper.java
commons/che-core-commons-gwt/src/main/java/org/eclipse/che/api/promises/client/js/Executor.java
commons/che-core-commons-gwt/src/main/java/org/eclipse/che/api/promises/client/js/JsPromise.java
commons/che-core-commons-gwt/src/main/java/org/eclipse/che/api/promises/client/js/JsPromiseError.java
commons/che-core-commons-gwt/src/main/java/org/eclipse/che/api/promises/client/js/Promises.java

IDEX-3474: Improve errors handling in Promises; add JavaDocs to org.eclipse.che.api.promises.* classes

---

che-core-git-impl-jgit/pom.xml
che-core-git-impl-jgit/src/main/java/org/eclipse/che/git/impl/jgit/ExternalStringsSource.java
che-core-git-impl-jgit/src/main/java/org/eclipse/che/git/impl/jgit/GitBasicAuthenticationCredentialsProvider.java
che-core-git-impl-jgit/src/main/java/org/eclipse/che/git/impl/jgit/GitProjectBasicAuthenticationImporter.java
che-core-git-impl-jgit/src/main/java/org/eclipse/che/git/impl/jgit/JGitConfigImpl.java
che-core-git-impl-jgit/src/main/java/org/eclipse/che/git/impl/jgit/JGitConnection.java
che-core-git-impl-jgit/src/main/java/org/eclipse/che/git/impl/jgit/JGitConnectionFactory.java
che-core-git-impl-jgit/src/main/java/org/eclipse/che/git/impl/jgit/JGitDiffPage.java
che-core-git-impl-jgit/src/main/java/org/eclipse/che/git/impl/jgit/JGitMergeResult.java
che-core-git-impl-jgit/src/main/java/org/eclipse/che/git/impl/jgit/Messages.java
che-core-git-impl-jgit/src/main/java/org/eclipse/che/git/impl/jgit/shared/JGitRebaseResponse.java
che-core-git-impl-jgit/src/main/java/org/eclipse/che/git/impl/jgit/ssh/SshUtil.java
pom.xml

Signed-off-by: Dror Cohen <dror.cohen@sap.com>

Initial JGit Implementation

---

che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/NativeGitConnection.java
che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/NativeGitConnectionFactory.java
che-core-git-impl-native/src/test/java/org/eclipse/che/git/impl/GitConnectionFactoryProvider.java

Problems is not correct deternination is module under git repository or not.
Now we detect it in two steps:
- firts we run git rev-parse --is-inside-work-tree for detecting is any git repository exist
- second we check that this repo under our virtaul file system control

IDEX-3713: GitMixin is not propagated to modules.

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/create/CreateWorkspacePresenter.java

match url like http://codenvy and don't show error message in case url field is empty

IDEX-3711:URL validation works wrong

---

platform-api-client-gwt/che-core-client-gwt-project/src/main/java/org/eclipse/che/api/project/gwt/client/ProjectServiceClient.java

@vparfonov This method is not deprecated for now

Remove deprecated annotation of update project method

---

platform-api/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryConstants.java
platform-api/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/impl/FactoryBaseValidator.java
platform-api/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/shared/dto/Ide.java
platform-api/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/shared/dto/OnProjectsLoaded.java
platform-api/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/builder/FactoryBuilderTest.java
platform-api/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/impl/FactoryBaseValidatorTest.java
platform-api/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/impl/TesterFactoryBaseValidator.java

Rename OnProjectOpened -> OnProjectsLoaded DTO

Rename OnProjectOpened -> OnProjectsLoaded DTO

---

platform-api/che-core-api-core/pom.xml
platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/DefaultHttpJsonRequest.java
platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/DefaultHttpJsonRequestFactory.java
platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/DefaultHttpJsonResponse.java
platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/HttpJsonRequest.java
platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/HttpJsonRequestFactory.java
platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/HttpJsonResponse.java
platform-api/che-core-api-core/src/test/java/org/eclipse/che/api/core/rest/DefaultHttpJsonRequestTest.java
platform-api/che-core-api-core/src/test/java/org/eclipse/che/api/core/rest/DefaultHttpJsonResponseTest.java
platform-api/che-core-api-core/src/test/java/org/eclipse/che/api/core/rest/TestService.java
platform-api/che-core-api-infrastructure-local/pom.xml
platform-api/che-core-api-infrastructure-local/src/main/java/org/eclipse/che/api/local/RemotePreferenceDao.java
platform-api/che-core-api-infrastructure-local/src/test/java/org/eclipse/che/api/local/RemotePreferenceDaoCompatibilityTest.java
platform-api/che-core-api-infrastructure-local/src/test/java/org/eclipse/che/api/local/RemotePreferenceDaoTest.java
platform-api/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/dao/PreferenceDao.java

Along with `RemotePreferenceDao` this PR contains new _builder-like_ class for requesting json content.
@skabashnyuk, @akorneta, @garagatyi, @sleshchenko check it out. 
I am going to add tests for `RemovePreferenceDao` so don't worry about it.

IDEX-3670: Add PreferenceDao which delegates calls to UserProfileService

---

commons/che-core-commons-gwt/src/main/java/org/eclipse/che/ide/websocket/AbstractMessageBus.java
commons/che-core-commons-gwt/src/main/java/org/eclipse/che/ide/websocket/MessageBus.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/bootstrap/WorkspaceComponent.java

Remove onOpenHandler after connection opened

Add method for removing onOpen handlers.

---

commands

I guess this file is useless and it was wrongly commited

Remove useless file

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/ProjectExplorerPresenter.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/smartTree/Tree.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/AttributeFilter.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/DefaultProjectManager.java

IDEX-3631: Fix creating module in project which was cloned with keep directory option.

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/perspectives/general/PerspectiveViewImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/perspectives/general/PerspectiveViewImpl.ui.xml
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/workspace/perspectives/general/AbstractPerspectiveTest.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/workspace/perspectives/project/ProjectPerspectiveTest.java

Resize terminal in Processes panel

IDEX-3153. Resize terminal in Processes panel

---

platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/ProjectConfigImpl.java

IDEX-3605: Imported project contains "storage" information

---

platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/ProjectConfigImpl.java

IDEX-3605: Add "storage" information to project

---

commons/che-core-commons-inject/src/main/java/org/eclipse/che/inject/CheBootstrap.java

IDEX-3611 Make CHE_LOCAL_CONF_DIR constant as public

---

ide/che-core-ide-app/pom.xml
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/CoreLocalizationConstant.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/DeleteItemAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/newresource/AbstractNewResourceAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/ProjectExplorerPresenter.java
ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties

@vparfonov @skabashnyuk please review

IDEX-3661: Ask to add to index when adding or deleting items

---

platform-api/che-core-api-vfs/src/main/java/org/eclipse/che/api/vfs/server/Path.java
platform-api/che-core-api-vfs/src/test/java/org/eclipse/che/api/vfs/server/PathTest.java

1- Better relativization in newPath, e.g. newPath("../abc")
2- Smarter reuse of ROOT
3- Slight improvement in toString() caching
4- Use standard Arrays.hashCode() in Path.hashCode()

Path improvements

---

platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/DefaultProjectManager.java

Some (most) logic of creating projects and adding modules to new folders is similar. I extracted the common logic into a single function to avoid double maintenance. A smaller part of this logic is also shared with converting a folder to a project.

Reuse code in DefaultProjectManager

---

platform-api-client-gwt/che-core-client-gwt-workspace/src/main/java/org/eclipse/che/api/workspace/gwt/client/WorkspaceServiceClientImpl.java
platform-api/che-core-api-account/pom.xml
platform-api/che-core-api-account/src/main/java/org/eclipse/che/api/account/server/AccountService.java
platform-api/che-core-api-account/src/main/java/org/eclipse/che/api/account/server/dao/Account.java
platform-api/che-core-api-account/src/main/java/org/eclipse/che/api/account/server/dao/AccountDao.java
platform-api/che-core-api-account/src/test/java/org/eclipse/che/api/account/AccountServiceTest.java

In this PR i: 
* Improved account model
* Added `AccountDao.exists` method
* Fixed `WorkspaceServiceClient` behaviour, it was sending 'null' string instead of null object in query parameters.

CLDIDE-2636: Improve account model

---

platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitProjectImporter.java
platform-api/che-core-api-project/pom.xml
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/BaseProjectModule.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/DefaultProjectManager.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectImporter.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectImporterInterceptor.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectManager.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectService.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ZipProjectImporter.java
platform-api/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/ProjectImporterInterceptorTest.java
platform-api/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/ProjectServiceTest.java

@vparfonov @evoevodin @mshaposhnik @sleshchenko

IDEX-3802: Configure project as blank by default after import

---

commons/che-core-commons-gwt/src/main/resources/org/eclipse/che/ide/ui/zeroclipboard/ZeroClipboard.css
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/theme/Theme.java
ide/che-core-ide-api/src/main/resources/org/eclipse/che/ide/api/ui/style.css
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/wizard/mainpage/MainPageViewImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projecttype/wizard/categoriespage/CategoriesPageViewImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/DarkTheme.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/LightTheme.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/list/CategoriesList.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/list/CategoryNodeElement.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/list/CategoryRenderer.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/toolbar/Utils.java
ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/list/CategoriesList.css
ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/toolbar/toolbar.css

IDEX-3667: create new command wizard

---

ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/menu/menu.css
ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/toolbar/toolbar.css

fix background color for tooltip

---

platform-api/che-core-api-vfs/src/main/java/org/eclipse/che/api/vfs/server/Path.java
platform-api/che-core-api-vfs/src/test/java/org/eclipse/che/api/vfs/server/PathTest.java

This pull request is backport of a commit from master https://github.com/codenvy/che-core/commit/abb1259581f4fc38c2426b85d9f41dd3e80463e9
1- Better relativization in newPath, e.g. newPath("../abc")
2- Smarter reuse of ROOT
3- Slight improvement in toString() caching
4- Use standard Arrays.hashCode() in Path.hashCode()
Change-Id: I93525f3fee1140e4f51fe6ae3c522c3f58ebcd92

CLDIDE-2656 : Path improvements

---

platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectService.java
platform-api/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/ProjectServiceTest.java

This pull request is backport  of a commit  from master https://github.com/codenvy/che-core/commit/6e647d5144dfa8ac42674dc185e84d2fbb3344c7

CLDIDE-2656 : project server get item safety 478

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/bootstrap/FactoryWorkspaceComponent.java
platform-api-client-gwt/che-core-client-gwt-factory/src/main/java/org/eclipse/che/api/factory/gwt/client/FactoryServiceClient.java
platform-api-client-gwt/che-core-client-gwt-factory/src/main/java/org/eclipse/che/api/factory/gwt/client/FactoryServiceClientImpl.java
platform-api/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryAcceptValidator.java
platform-api/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryService.java
platform-api/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/impl/FactoryAcceptValidatorImpl.java

- Removed unused legacy param;
- Added "validate" option to factory client;
- Fix find by attribute service

CLDIDE-2645 accept named factories

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/project/node/FileReferenceNode.java
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/texteditor/EmbeddedTextEditorPresenter.java

@vparfonov @skabashnyuk @evidolob 
(http://s38-temporary-files.radikal.ru/f1d3a237b8634fb5b32ce82579f15f17/-929206895.png)

Display artifact id as file name for pom.xml files

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/theme/Theme.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/ProjectExplorerViewImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/project/node/AbstractProjectBasedNode.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/DarkTheme.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/LightTheme.java

Like in IDEA, see screenshots attached below:
@vparfonov @skabashnyuk @ashumilova

Mark each Test folder child and Jar child with different background color

---

platform-api/che-core-api-vfs/src/main/java/org/eclipse/che/api/vfs/server/search/LuceneSearcher.java

IDEX-3688: skip indexing files which aren't filtered

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/CoreLocalizationConstant.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/DeleteItemAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/OpenFileAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/PasteAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/WorkspaceSnapshotCreator.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/bootstrap/FactoryWorkspaceComponent.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/bootstrap/WorkspaceComponent.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/editor/EditorAgentImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/newresource/AbstractNewResourceAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/ProjectExplorerPresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/wizard/ImportProjectNotificationSubscriberImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/wizard/mainpage/MainPagePresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/upload/file/UploadFilePresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/upload/folder/UploadFolderFromZipPresenter.java
ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/actions/WorkspaceSnapshotCreatorTest.java
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/JsEditorConstants.java
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/texteditor/EmbeddedTextEditorPresenter.java

IDEX-3876: Change the titles and messages of all Che notifications

---

che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/NativeGit.java
che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/NativeGitConnection.java
che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/commands/ShowFileContentCommand.java
ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/smartTree/TreeStyles.css
platform-api-client-gwt/che-core-client-gwt-git/src/main/java/org/eclipse/che/api/git/gwt/client/GitServiceClient.java
platform-api-client-gwt/che-core-client-gwt-git/src/main/java/org/eclipse/che/api/git/gwt/client/GitServiceClientImpl.java
platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitConnection.java
platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitService.java
platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/shared/ShowFileContentRequest.java
platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/shared/ShowFileContentResponse.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/ShowFileContentTest.java

@skabashnyuk @vparfonov @sleshchenko  please review

IDEX-3674: Add git show command

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/DeleteItemAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/newresource/AbstractNewResourceAction.java

IDEX-3939: Change buttons name to 'Yes/No' in add to git index dialog

---

platform-api/che-core-api-core/pom.xml
platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/DefaultHttpJsonRequest.java
platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/DefaultHttpJsonRequestFactory.java
platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/DefaultHttpJsonResponse.java
platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/HttpJsonRequest.java
platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/HttpJsonRequestFactory.java
platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/HttpJsonResponse.java
platform-api/che-core-api-core/src/test/java/org/eclipse/che/api/core/rest/DefaultHttpJsonRequestTest.java
platform-api/che-core-api-core/src/test/java/org/eclipse/che/api/core/rest/DefaultHttpJsonResponseTest.java
platform-api/che-core-api-core/src/test/java/org/eclipse/che/api/core/rest/TestService.java

This pull request is down port the HttpJsonRequest.

Downport 3.x http json request

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/debug/BreakpointStateEvent.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/debug/BreakpointStateEventHandler.java
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/debug/BreakpointManagerImpl.java

When JVM activate breakpoint then respective mark should be set by BreakpointManager

IDEX-3691: manage deferred breakpoints

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/action/Separator.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/dropdown/DropDownHeaderWidget.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/dropdown/DropDownHeaderWidgetImpl.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/dropdown/DropDownListFactory.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/dropdown/SimpleListElementAction.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/toolbar/PopupMenu.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/toolbar/Utils.java
ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/dropdown/DropdownList.css
ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/toolbar/popup-menu.css
ide/che-core-ide-ui/src/test/java/org/eclipse/che/ide/ui/dropdown/SimpleListElementActionTest.java

IDEX-3852: command selector improvements

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/find/FindActionPresenter.java

https://jira.codenvycorp.com/browse/IDEX-3970
@vparfonov

IDEX-3970: exclude recent files from action list

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/FindReplaceAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/local/LocalZipImporterPagePresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/wizard/ImportWizard.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/projectimport/local/LocalZipImporterPagePresenterTest.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/projectimport/wizard/ImportWizardTest.java
platform-api-client-gwt/che-core-client-gwt-vfs/pom.xml
platform-api-client-gwt/che-core-client-gwt-vfs/src/main/java/org/eclipse/che/api/vfs/gwt/client/VfsServiceClient.java
platform-api-client-gwt/che-core-client-gwt-vfs/src/main/java/org/eclipse/che/api/vfs/gwt/client/VfsServiceClientImpl.java

IDEX-3760: Fix import project after page refresh

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/inject/FileTypeModule.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/imageviewer/ImageViewer.java
ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/Core.css
ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/imageviewer/imageViewer.css
platform-api/che-core-api-core/src/main/resources/content-types.properties

fix image viewer's bug

---

platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/Constants.java
platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceHooks.java
platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceManager.java
platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/event/MachineStateListener.java
platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/RuntimeWorkspaceImpl.java
platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/UsersWorkspaceImpl.java
platform-api/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceManagerTest.java

1. Improve `WorkspaceManager`(docs + new methods structure + tests)
2. Document workspace REST API with swagger annotations

IDEX-3811: Document workspace REST API

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/CloseCurrentFile.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/StandardComponentInitializer.java

New hotkey binded to:
Win/Linux: Alt+w
Mac: Ctrl+w
@vparfonov

IDEX-3431: Add close file hot key

---

platform-api-client-gwt/che-core-client-gwt-project/pom.xml
platform-api/che-core-api-project/pom.xml
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/shared/dto/ProjectTemplateDescriptor.java
platform-api/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/ProjectTemplateDescriptionLoaderTest.java
platform-api/che-core-api-project/src/test/resources/che-templates/embed_type.json

Change-Id: Iec1bad07877c6e52c50948e8b1bc7b9592a244ce

IDEX-4013 Allow to store workspace commands into a project template

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/create/CreateWorkspacePresenter.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/workspace/create/CreateWorkspacePresenterTest.java

Rename dev-machine in IDE to ws-machine

IDEX-3882. Rename dev-machine in IDE to ws-machine

---

commons/che-core-commons-gwt/src/main/java/org/eclipse/che/ide/ui/loaders/initialization/InitialLoadingInfo.java
platform-api-client-gwt/che-core-client-gwt-machine/src/main/java/org/eclipse/che/api/machine/gwt/client/ExtServerStateController.java

Rename 'extension server' by 'Workspace agent'

IDEX-3890. Rename 'extension server' by 'Workspace agent'

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/event/project/CurrentProjectChangedEvent.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/CoreLocalizationConstant.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/ProjectExplorerPresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/synchronize/ChangeLocationWidget.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/synchronize/ProjectConfigSynchronizationListener.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/wizard/ImportProjectNotificationSubscriberImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/wizard/ImportWizard.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/wizard/ProjectImporter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projecttype/wizard/presenter/ProjectWizardPresenter.java
ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/part/explorer/project/synchronize/ChangeLocationWidgetTest.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/part/explorer/project/synchronize/ProjectConfigSynchronizationListenerTest.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/projectimport/wizard/ProjectImporterTest.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/AttributeFilter.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/DefaultProjectManager.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/DtoConverter.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectManager.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectService.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectTypes.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/type/ProjectTypeRegistry.java
platform-api/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/ProjectServiceTest.java
platform-api/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/type/ProjectTypeTest.java

IDEX-3991: Synchronize workspace master and VFS

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/theme/Theme.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/DarkTheme.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/LightTheme.java
platform-api/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/model/impl/CommandImpl.java
platform-api/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/shared/dto/CommandDto.java
platform-api/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/machine/Command.java
platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/DtoConverter.java

@slemeur @vparfonov @ashumilova @skabashnyuk

IDEX-3924: Display preview URL in console panel

---

platform-api-client-gwt/che-core-client-gwt-user/src/main/java/org/eclipse/che/api/user/gwt/client/UserServiceClient.java
platform-api-client-gwt/che-core-client-gwt-user/src/main/java/org/eclipse/che/api/user/gwt/client/UserServiceClientImpl.java
platform-api/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/UserService.java
platform-api/che-core-api-user/src/test/java/org/eclipse/che/api/user/server/UserServiceTest.java

In method find I've replaced query parameter email with query parameter alias.
It will call the same UserDao method findByAlias.

IDEX-4000 Change email to alias in UserService

---

platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceManager.java

IDEX-4006: Fix error message

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/CoreLocalizationConstant.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/Resources.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/hotkeys/dialog/HotKeysDialogPresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/hotkeys/dialog/HotKeysDialogView.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/hotkeys/dialog/HotKeysDialogViewImpl.java
ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties
ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/hotkeys/print_template.html

Make it possible to print all key bindings on printer

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/app/AppContext.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/importer/AbstractImporter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/CoreLocalizationConstant.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/ProjectExplorerPresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/synchronize/ProjectConfigSynchronizationListener.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/ErrorMessageUtils.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/wizard/ProjectImporter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/wizard/ProjectResolver.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/wizard/ProjectUpdater.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projecttype/wizard/ProjectWizard.java
ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/part/explorer/project/synchronize/ProjectConfigSynchronizationListenerTest.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/projectimport/wizard/ProjectImporterTest.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/projectimport/wizard/ProjectUpdaterTest.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/projecttype/wizard/ProjectWizardTest.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/smartTree/NodeLoader.java
ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/smartTree/Tree.java

IDEX-4046: Show synchronize dialog when user open node

---

platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/DownloadFileResponseFilter.java
platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/JAXRSDownloadFileResponseFilter.java
platform-api/che-core-api-core/src/main/java/org/eclipse/che/everrest/EverrestDownloadFileResponseFilter.java
platform-api/che-core-api-core/src/test/java/org/eclipse/che/everrest/DownloadFileResponseFilterTest.java

Change-Id: Ied519730b6cbab055305f13285874d8bf28dc703

IDEX-4019 Introduce a new filter to provide download of the result

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/search/presentation/FindResultPresenter.java
ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties

@vparfonov @ashumilova 
this need to visual identify tabs if we use find text and usages in the same time

IDEX-4093: Update tabs title

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/wizard/mainpage/MainPagePresenter.java
platform-api-client-gwt/che-core-client-gwt-project/src/main/java/org/eclipse/che/api/project/gwt/client/ProjectImportersServiceClient.java
platform-api-client-gwt/che-core-client-gwt-project/src/main/java/org/eclipse/che/api/project/gwt/client/ProjectImportersServiceClientImpl.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectImportersService.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/shared/dto/ProjectImporterData.java

Do not merge until properties are added

IDEX-3295 Select Git importer by default

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/theme/Theme.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/DarkTheme.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/LightTheme.java
ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/notification/notification.css

How it looks on Dark Theme
The same on the Light Theme
@ashumilova

IDEX-4028: Refine notification popups on light theme

---

commons/che-core-commons-gwt/src/main/java/org/eclipse/che/ide/util/dom/Elements.java

Fix potential NPE when OMSVGSVGElement processed

---

ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/list/CategoriesList.css

IDEX-4072: Add icons in command popup

---

platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/DefaultHttpJsonRequest.java
platform-api/che-core-api-machine/pom.xml
platform-api/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/WsAgentLauncherImpl.java
platform-api/che-core-api-machine/src/test/java/org/eclipse/che/api/machine/server/WsAgentLauncherImplTest.java

Throw exception if pinging was unsuccessful and there is no time to ping more.
Refactor tests of ws agent pinging.
Add debug log.
@skabashnyuk

Fix WS agent pinging

---

ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/texteditor/EmbeddedTextEditorPresenter.java

Editor now has ability to provide into selection model current opened file. And Current class fqn provider now listen selection changed events to have ability provide fqn on selected file in Project Explorer or another place.
Screencast: https://slack-files.com/T02G3VAG4-F0JF7CB0T-650823b3be
Related PR: https://github.com/codenvy/che-plugins/pull/549

Add ability to configure selection with opened file in editor

---

platform-api/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/WsAgentLauncherImpl.java
platform-api/che-core-api-machine/src/test/java/org/eclipse/che/api/machine/server/WsAgentLauncherImplTest.java

fix WS agent ping test

---

platform-api/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/UserService.java
platform-api/che-core-api-user/src/test/java/org/eclipse/che/api/user/server/UserServiceTest.java

@skabashnyuk Please review my changes

CDEC-503 Introduce user.self.creation.allowed

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/theme/Theme.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/DarkTheme.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/LightTheme.java
ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/smartTree/TreeStyles.css

IDEX-4077: Improve selected states in project explorer

---

commons/che-core-commons-gwt/src/main/resources/org/eclipse/che/ide/ui/tree/Tree.css

IDEX-4078: Improve selected states in console panel

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/ProjectExplorerPresenter.java

Update actions in Git menu immediatelly after initializing repo

---

platform-api/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticator.java
platform-api/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticatorProviderImpl.java

@skabashnyuk Please review my changes

CLDIDE-2561 Add not configured state for OAuthAuthenticator

---

platform-api-client-gwt/che-core-client-gwt-factory/src/main/java/org/eclipse/che/api/factory/gwt/client/FactoryServiceClient.java
platform-api-client-gwt/che-core-client-gwt-machine/src/main/java/org/eclipse/che/api/machine/gwt/client/MachineServiceClient.java
platform-api-client-gwt/che-core-client-gwt-machine/src/main/java/org/eclipse/che/api/machine/gwt/client/MachineServiceClientImpl.java
platform-api-client-gwt/che-core-client-gwt-machine/src/main/java/org/eclipse/che/api/machine/gwt/client/RecipeServiceClient.java
platform-api-client-gwt/che-core-client-gwt-project/src/main/java/org/eclipse/che/api/project/gwt/client/ProjectServiceClient.java
platform-api-client-gwt/che-core-client-gwt-project/src/main/java/org/eclipse/che/api/project/gwt/client/ProjectTypeServiceClient.java
platform-api-client-gwt/che-core-client-gwt-workspace/src/main/java/org/eclipse/che/api/workspace/gwt/client/WorkspaceServiceClient.java
platform-api-client-gwt/che-core-client-gwt-workspace/src/main/java/org/eclipse/che/api/workspace/gwt/client/WorkspaceServiceClientImpl.java

Improve JavaDoc on GWT-clients for Platform API Services

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/ProjectConfigurationAction.java

IDEX-3891: disable 'Project Configuration...' action when no project is selected

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/CopyAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/CutAction.java

IDEX-2998: Can not perform Ctrl+C, Ctrl+V, operations into editor

---

platform-api/che-core-api-machine/pom.xml
platform-api/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/MachineManager.java
platform-api/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/MachineService.java

@skabashnyuk @vparfonov @evoevodin

IDEX-4194: add swagger annotations for machine API

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/parts/AbstractPartPresenter.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/selection/Selection.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/context/AppContextImpl.java
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/texteditor/EmbeddedTextEditorPresenter.java

Selection improvements

---

ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/texteditor/ContentInitializedHandler.java
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/texteditor/EditorWidget.java
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/texteditor/EmbeddedTextEditorPresenter.java

IDEX-3955:Add handler for catching event then content inject to Editor Widget

---

platform-api/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/Constants.java
platform-api/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/MachineManager.java
platform-api/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/MachineService.java

Add links
Return 400 if required parameter is missing instead of 403
@skabashnyuk @evoevodin

improve Machine API

---

platform-api/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/MachineManager.java

IDEX-4092: destroy docker machine if ws agent pinging fails

---

platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectTypeService.java

Add swagger annotations to the `ProjectTypeService`.
@skabashnyuk, @garagatyi please review

IDEX-2769: Document ProjectTypeService

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/project/wizard/ImportProjectNotificationSubscriberFactory.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/project/wizard/ProjectNotificationSubscriber.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/RenameItemAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/inject/CoreGinModule.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/project/node/resource/ProjectConfigProcessor.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/local/LocalZipImporterPagePresenter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/wizard/ProjectImporter.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/wizard/ProjectNotificationSubscriberImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/wizard/ProjectResolver.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/wizard/ProjectUpdater.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/projectimport/local/LocalZipImporterPagePresenterTest.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/projectimport/wizard/ProjectImporterTest.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/projectimport/wizard/ProjectUpdaterTest.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/DefaultProjectManager.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectService.java
platform-api/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/ProjectServiceTest.java

Add rename project feature.
@vparfonov

IDEX-4155: Add ability to rename project via Project wizard.

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/parts/PartStackUIResources.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/parts/PartStackView.java
ide/che-core-ide-api/src/main/resources/org/eclipse/che/ide/api/parts/partstack.css
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/PartStackViewImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/widgets/editortab/EditorTabWidget.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/widgets/partbutton/PartButtonWidget.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/widgets/partbutton/PartButtonWidget.ui.xml
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/WorkBenchPartControllerImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/WorkBenchResources.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/perspectives/general/PerspectiveViewImpl.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/perspectives/general/PerspectiveViewImpl.ui.xml
ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/workspace/perspectives/general/WorkBench.css
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/part/PartStackViewImplTest.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/part/widgets/editortab/EditorTabWidgetTest.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/part/widgets/partbutton/PartButtonWidgetTest.java

Optimize stretching tabs by title length.
Previous PR  #647 was created by fork. To avoid streching git history, new PR was made for this functionality.
@ashumilova @skabashnyuk

IDEX-4034: Refine part tabs

---

platform-api-client-gwt/che-core-client-gwt-vfs/src/main/java/org/eclipse/che/api/vfs/gwt/client/VfsServiceClientImpl.java

IDEX-4149: Fix bug related to open project tree in some case

---

che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/NativeGitConnection.java
che-core-git-impl-native/src/main/java/org/eclipse/che/git/impl/nativegit/commands/LogCommand.java
platform-api-client-gwt/che-core-client-gwt-git/src/main/java/org/eclipse/che/api/git/gwt/client/GitServiceClient.java
platform-api-client-gwt/che-core-client-gwt-git/src/main/java/org/eclipse/che/api/git/gwt/client/GitServiceClientImpl.java
platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/shared/LogRequest.java
platform-api/che-core-api-git/src/test/java/org/eclipse/che/git/impl/LogTest.java

@vparfonov  @skabashnyuk please review

IDEX-3928: Add file filter to Git log command

---

ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/popup/PopupWidget.java

IDEX-4164: don't remove popup element form the parent if it's null

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/editor/EditorAgentImpl.java
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/reconciler/ReconcilerWithAutoSave.java
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/reconciler/ReconcilingStrategy.java
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/texteditor/EmbeddedTextEditorPresenter.java
ide/che-core-ide-jseditor/src/main/resources/org/eclipse/che/ide/jseditor/JsEditor.gwt.xml

This is need for avoiding not needed request to reconcile already removed/closed files

Uninstall reconciler for removed/closed files

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/RenameItemAction.java
platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/DefaultProjectManager.java

IDEX-4256: Fix rename a file

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/find/FindActionPresenter.java

IDEX-847: Fix actions filtering in Find Action

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/LightTheme.java

IDEX-4143: Improve light-theme commands outputs

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/recent/RecentFileAction.java

IDEX-4278: Provide unique action id for recent files

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/theme/Theme.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/DarkTheme.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/LightTheme.java

@slemeur @ashumilova @vparfonov

IDEX-4159. Improve styles for search blocks

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/project/node/HasProjectConfig.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/project/tree/VirtualFileImpl.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/project/tree/VirtualFileInfo.java
ide/che-core-ide-jseditor/pom.xml
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/debug/BreakpointManagerImpl.java

@vparfonov @dimasnurenko @evidolob @azatsarynnyy

IDEX-4060: add a custom implementation for VirtualFile

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/menu/ContextMenu.java

IDEX-3731: Fix context menu is out of screen

---

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/parts/AbstractPartPresenter.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/parts/PartPresenter.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/parts/Perspective.java
ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/parts/PerspectiveManager.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/ExpandEditorAction.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/perspectives/general/AbstractPerspective.java
ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/perspectives/project/ProjectPerspective.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/workspace/perspectives/general/AbstractPerspectiveTest.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/workspace/perspectives/general/PerspectiveManagerTest.java
ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/workspace/perspectives/project/ProjectPerspectiveTest.java
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/editoradapter/DefaultEditorAdapter.java
ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/texteditor/EmbeddedTextEditorPresenter.java

IDEX-3779: Fix reset cursor position in editor after switching perspective

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/bootstrap/WorkspaceComponent.java
platform-api-client-gwt/che-core-client-gwt-machine/src/main/java/org/eclipse/che/api/machine/gwt/client/ExtServerStateController.java

IDEX-4111: Fix showing several messages "Workspace agent started".

---

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/perspectives/general/AbstractPerspective.java

IDEX-4307: Fix error initialization IDE pop-up
