codenvy/che-core

ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/toolbar/ActionButton.java, ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/toolbar/ActionPopupButton.java, ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/toolbar/ToolbarResources.java, ide/che-core-ide-ui/src/main/resources/org/eclipse/che/ide/ui/toolbar/toolbar.css
Tooltip is now consists of two divs, and when it's about to cross the border, it will shift to the right (like in chrome).
=> IDEX-2344 Tooltip will not cross the right border of browser

platform-api/che-core-api-vfs/src/main/java/org/eclipse/che/api/vfs/server/search/LuceneSearcher.java
Hello,
I would like to enhance Lucene searcher capabilities therefore I did following changes:
1. queryParser.setAllowLeadingWildcard(true) enables performing contains query ( like *uer* )
2. SimpleAnalyzer uses LetterTokenizer with LowerCaseFilter, that means that it creates tokens by broking a text by non-letter characters, therefore in current implementation it is not possible to search for the text containing special characters. Using WhitespaceTokenizer solves this issue as it creates tokens by broking a text by whitespace.
Thanks & Regards,
Rima
=> Fixes that allow to search 1. for special characters 2. contains query

platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/FolderEntry.java, platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectService.java, platform-api/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/ProjectServiceTest.java
Hello,
Currently, the getTree() api does not include file children in it's response (only folders); to get the files we will need to traverse the tree by calling getChildren() api repeatedly.
So, in order for us to have the functionality we need, I would like to suggest a small addition to the getTree() api (GET /project/{ws-id}/tree/{parent:.*})
I would like to add another query param: ?includeFiles (which will be set to false by default); this param will indicate whether or not to include file children in the result tree.
I've made the relevant changes in: 
platform-api\che-core-api-project\src\main\java\org\eclipse\che\api\project\server\ProjectService.java
and in:
platform-api\che-core-api-project\src\main\java\org\eclipse\che\api\project\server\FolderEntry.java
I've tested it …
=> add support for include files in getTree() of project-api

platform-api/che-core-api-dto/src/main/java/org/eclipse/che/dto/generator/DtoImpl.java, platform-api/che-core-api-dto/src/main/java/org/eclipse/che/dto/generator/DtoImplClientTemplate.java, platform-api/che-core-api-dto/src/main/java/org/eclipse/che/dto/generator/DtoImplServerTemplate.java, platform-api/che-core-api-dto/src/main/java/org/eclipse/che/dto/shared/JsonFieldName.java, platform-api/che-core-api-dto/src/test/java/org/eclipse/che/dto/ServerDtoTest.java, platform-api/che-core-api-dto/src/test/java/org/eclipse/che/dto/definitions/DtoWithFieldNames.java
A new annotation, \@JsonFieldName, allow defining it
=> Allow defining custom JSON field names for DTO interfaces

che-core-vfs-impl/src/main/java/org/eclipse/che/vfs/impl/fs/FSMountPoint.java, che-core-vfs-impl/src/main/java/org/eclipse/che/vfs/impl/fs/VirtualFileImpl.java, platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/FileEntry.java, platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/FolderEntry.java, platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectService.java, platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/VirtualFileEntry.java, platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/shared/dto/CopyOptions.java, platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/shared/dto/MoveOptions.java, platform-api/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/ProjectServiceTest.java, platform-api/che-core-api-vfs/src/main/java/org/eclipse/che/api/vfs/server/VirtualFile.java, platform-api/che-core-api-vfs/src/main/java/org/eclipse/che/api/vfs/server/impl/memory/MemoryVirtualFile.java
Hello,
I created this pull request to address the issue described in my previous message to the mailing list
regarding the need to enable copy/move with rename operations to be conducted by a single REST call.
Summary of changes:
* Changes were made to both Copy and Move service methods in che-core-api-project: an additional argument was added, CopyOptions/MoveOptions respectively.
* The body of both services is now in the form of (application/json) { “name” : [the new name to set] , “overwrite” : [true/false] }
* The inclusion of this body is not mandatory so the API is not broken, it’s absence results in previous system behavior for copy/move services.
* Changes were made to org.eclipse.che.vfs.imple.fs project: To be able to pass along the new name and overwrite options, key methods …
=> Copy move with overwrite

platform-api/che-core-api-dto/pom.xml, platform-api/che-core-api-dto/src/main/java/org/eclipse/che/dto/generator/DtoImpl.java, platform-api/che-core-api-dto/src/main/java/org/eclipse/che/dto/generator/DtoImplClientTemplate.java, platform-api/che-core-api-dto/src/main/java/org/eclipse/che/dto/generator/DtoImplServerTemplate.java, platform-api/che-core-api-dto/src/test/java/org/eclipse/che/dto/ServerDtoTest.java, platform-api/che-core-api-dto/src/test/java/org/eclipse/che/dto/definitions/DtoWithAny.java
1- Serialzie and de-serialize JsonElement properties as raw JSONs
2- Deep-copy them in the generated copy constructors
3- Avoid redundant copying in fromJsonString() and toJson() cases
=> Support DTOs with properties typed 'any'

platform-api/che-core-api-builder/src/main/java/org/eclipse/che/api/builder/BuildQueue.java, platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/RemoteServiceDescriptor.java, platform-api/che-core-api-runner/src/main/java/org/eclipse/che/api/runner/RunQueue.java
- Use HttpJsonHelper for the rest call (this also makes sure the response
structure is valid)
- Pass current EnvironmentContext to executor.execute when registering
pre-configured builders and runners
=> Send token in RemoteServiceDescriptor.isAvailable

platform-api/che-core-api-dto/src/main/java/org/eclipse/che/dto/generator/DtoImplServerTemplate.java, platform-api/che-core-api-dto/src/test/java/org/eclipse/che/dto/ServerDtoTest.java
previously this failed with NPE
Change-Id: Id0de7b3a51bb3b98252388185878913fa40897c4
=> Support NULL 'any' properties in DTO cloning

commons/che-core-commons-lang/src/main/java/org/eclipse/che/commons/lang/reflect/ParameterizedTypeImpl.java, platform-api/che-core-api-dto/src/main/java/org/eclipse/che/dto/server/DtoFactory.java
According to issue #206, we can remove code overhead by making these changes.
But, it is still a question - Will this class provide the ```ownerType``` variable's instantiation through static generation methods. If so, than all these changes are inappropriate, and the different approach should be used (there should be static generation methods with three parameters):
```
public static ParameterizedType newParameterizedType(Type ownerType, 
Class<?> rawType, Type typeArgument) {
return new ParameterizedTypeImpl(ownerType, rawType, typeArgument);
} 
```
and
```
public static ParameterizedType newParameterizedType(Type ownerType, 
Class<?> rawType, Type... typeArgument) {
return new ParameterizedTypeImpl(ownerType, rawType, typeArgument);
} 
```
And class will need its ```private final Type …
```
=> [#206 - issue] Private constructors changed in ParameterizedTypeImpl.java

platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/DefaultProjectManager.java, platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/Project.java, platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectManager.java, platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectService.java
This allow reusing the whole logic of updateProject/delete/rename from inside the server, without the need for loop-back calls to ProjectService. This further reduces the mix-up of service layer with server logic.
Change-Id: I7cdf4c71f11dae24316da4f21b346cf2b181d8a0
=> Move complex logic from ProjectServce to ProjectManager

platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/CodenvyJsonProvider.java
All DTO objects and JsonSerializable will be serialized in the same way
Some background.
Server side DTO do not have @Dto annotation. This annotation is located in the interface which implements this particular class.
Server DTO classes has annotation @org.eclipse.che.dto.shared.DTOImpl and they are implements JsonSerializable interface.
Behind the scene DtoFactory.getInstance().toJson(t) use JsonSerializable to convert object to json.
To make sure that all objects serialized in the same thay I've reworked  codition.
So from now we check if object implement JsonSerializable interface instead of checking of DTO annotation.
Signed-off-by: Sergii Kabashniuk <skabashnyuk@codenvy.com>
=> IDEX-2603 All DTO objects and JsonSerializable will be serialized in the same way.

che-core-vfs-impl/pom.xml, che-core-vfs-impl/src/main/java/org/eclipse/che/vfs/impl/fs/FSMountPoint.java, che-core-vfs-impl/src/main/java/org/eclipse/che/vfs/impl/fs/VirtualFileSystemFSModule.java, che-core-vfs-impl/src/test/java/org/eclipse/che/vfs/impl/fs/RenameTest.java
In 4.0 we are not relying on vfs permission so we can simply return any-any permission
for all users. We need to return something because UI is still relying on this information.
=> IDEX-3267 Return any-any permissions for all VFS entries

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/ProjectExplorerPresenter.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/ProjectExplorerView.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/ProjectExplorerViewImpl.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/explorer/project/SearchNodeHandler.java
Add ability to configure editor behaviour
in case when we try to update project tree.
By default editor tries to close opened file
if it was removed after reloading. Now it
become possible to configure this behaviour.
This fix needed for java rename refactoring
feature.
@vparfonov
=> Skip editor close when node removed

platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/RuntimeWorkspaceRegistry.java, platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceManager.java, platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java, platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/EnvironmentImpl.java, platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/ProjectConfigImpl.java, platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/RuntimeWorkspaceImpl.java, platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/SourceStorageImpl.java, platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/UsersWorkspaceImpl.java, platform-api/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/RuntimeWorkspaceRegistryTest.java, platform-api/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceManagerTest.java
WorkspaceManager was returning RuntimeWorkspace instance with __STARTING__ status each time when workspace start was performed. Now it checks if workspace is stopped before it starts as well as `RuntimeWorkspaceRegistry` does. It this PR i also added new `update` method to the registry + fixed methods behaviour when registry is stopping workspaces.
It is not consistent with 4.0 because it requires merge conflict fixes, but i will do it ASAP.
@skabashnyuk, @garagatyi, @akorneta, @sleshchenko can you please review this changes.
=> IDEX-3326: Fix wrong behaviour of WorkspaceManager start method 

platform-api/che-core-api-builder/src/main/java/org/eclipse/che/api/builder/RemoteTask.java, platform-api/che-core-api-builder/src/main/java/org/eclipse/che/api/builder/internal/SlaveBuilderService.java, platform-api/che-core-api-builder/src/main/java/org/eclipse/che/api/builder/internal/SourcesManagerImpl.java
Each RemoteTask & SourcesManagerImpl request goes with authorization token which allows us to protect `SlaveBuilderService` from unauthorized calls.
=> CLDIDE-2598: Use token in  RemoteTask & SourcesManagerImpl calls

platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/RuntimeWorkspaceRegistry.java, platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceHooks.java, platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceManager.java, platform-api/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/RuntimeWorkspaceRegistryTest.java, platform-api/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceManagerTest.java
We need to know environment name which is used for start as well as account id to analyze resources and related stuff.
=> IDEX-3406: Use environment name in WorkspaceHooks#beforeStart method

ide/che-core-ide-app/src/test/java/org/eclipse/che/util/TestGeneratorUtils.java, ide/che-core-ide-generators/src/test/java/org/eclipse/che/util/TestGeneratorUtils.java
Remove `* along with this program; if not, see<http://www.gnu.org/licenses/>.\n" + "*/ \n` line from tests as it refers to GPL resources
=> IDEX-3429: Remove links to GPL resources

ide/che-core-ide-app/pom.xml
This is pull request for issue https://jira.codenvycorp.com/browse/CLDIDE-2622
The scope of dependency com.google.gwt:gwt-dev was changed from "test" to "provided".
=> CLDIDE-2622 : Change the scope dependency com.google.gwt:gwt-dev for fix javadoc generation

platform-api/che-core-api-dto/src/main/java/org/eclipse/che/dto/generator/DtoImplServerTemplate.java, platform-api/che-core-api-dto/src/main/java/org/eclipse/che/dto/server/DtoFactory.java, platform-api/che-core-api-dto/src/main/java/org/eclipse/che/dto/server/JsonArrayImpl.java, platform-api/che-core-api-dto/src/main/java/org/eclipse/che/dto/server/JsonSerializable.java, platform-api/che-core-api-dto/src/main/java/org/eclipse/che/dto/server/JsonStringMapImpl.java
this is more efficient than using the only API that is currently available
'toJson()'. It returns a string which means two redundant serializations must
be done if the JsonElement is needed directly:
DTO->JsonElement->String->JsonElement
Change-Id: I78cbfe0fd54b28d8b14ba53bc35b8cfd891f19bc
=> Expose direct API for converting DTOs to JSON objects

platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/notification/EventService.java
Currently the only way to subscribe to an event is by providing an implementation of EventSubscriber whose only generic type argument is a concrete event class. Passing generic event subscribers fails, e.g.:
class MySubsriber<T> implements EventSubscriber<T> {
@Override
public void onEvent(T event) { ... }
}
class MyController {
@Inject
EventService eventService;
@PostConstruct
public void init() {
eventService.subscribe(new MySubsriber<MyEvent>());
}
}
the above example will fail because the current code looks for generic type arguments that are concrete classes. It also fails in other cases like lambda expressions and factory functions. My patch allows generalized event subscription like this:
eventService.subscribe(new MySubsriber<MyEvent>(), MyEvent.class);
=> Allow subscribing to a specific event type explicitly in EventService

platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/notification/EventService.java, platform-api/che-core-api-dto/src/main/java/org/eclipse/che/dto/server/DtoFactory.java, platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/DefaultProjectManager.java
This is a pull request for part of issue the https://jira.codenvycorp.com/browse/IDEX-3511
This the pull request replace to usage org.eclipse.che.commons.lang.cache.Cache to Guava Cache in the classes DtoFactory, EventService, DefaultProjectManager.
=> IDEX-3511 : Use Guava cache instead of org.eclipse.che.commons.lang.cache.Cache in classes DtoFactory, EventService, DefaultProjectManager

commons/che-core-commons-gwt/src/main/resources/org/eclipse/che/ide/Commons.gwt.xml
@vparfonov @evidolob @azatsarynnyy I removed settings for ie9. 
And I have question: Will it work https://github.com/codenvy/che-core/blob/784fed052d53ea3d98c1232936afeb68a2d0e90b/commons/che-core-commons-gwt/src/main/resources/org/eclipse/che/ide/Commons.gwt.xml#L46-L54 if we don't set user agent to android and iphone?
=> Remove gwt compiling for IE9

commons/che-core-commons-gwt/src/main/java/org/eclipse/che/api/promises/client/callback/PromiseHelper.java, commons/che-core-commons-gwt/src/main/java/org/eclipse/che/ide/rest/AsyncRequest.java, platform-api-client-gwt/che-core-client-gwt-machine/src/main/java/org/eclipse/che/api/machine/gwt/client/MachineServiceClient.java, platform-api-client-gwt/che-core-client-gwt-machine/src/main/java/org/eclipse/che/api/machine/gwt/client/MachineServiceClientImpl.java
* Added ability to get result of AsyncRequest via Promise.
* Deprecated PromiseHelper since AsyncRequest#send() returns Promise with request result.
* Refactored AsyncRequest class to make it more readable.
* Reworked MachineServiceClientImpl in order to get result of asynchronous requests via Promise. Avoid using deprecated PromiseHelper.
* Removed obsolete methods from MachineServiceClient.
=> Improve using of async requests

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/bootstrap/FactoryWorkspaceComponent.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/bootstrap/WorkspaceComponent.java
In situation during creating workspace from factory when workspace with specified name
already exist we had unhandled exception and abnormal behavior of ide.
=> CLDIDE-2631: Fix wrong behavior during creating workspace from factory

platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectService.java, platform-api/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/ProjectServiceTest.java
If the item is missing, return 404 instead of 500 NPE
If the item is not inside a project, retrieve without 500 NPE
=> Safe /project/{ws}/item/{path} if parent project or item is missing

platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectService.java, platform-api/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/ProjectServiceTest.java
If "generatorDescription" is null when creating a module via ProjectService, it fails with 500 NullPointerException. This patch adds null safety.
=> Null "generatorDescription" safety in ProjectService.createModule()

ide/che-core-ide-app/pom.xml
It will avoid static analyzers in IDE's to propose use java 8 features. Because java 8 isn't available on the client side.
@vparfonov @skabashnyuk WDYT about it?
=> Source level

che-core-vfs-impl/src/main/java/org/eclipse/che/vfs/impl/fs/GitUrlResolver.java, che-core-vfs-impl/src/test/java/org/eclipse/che/vfs/impl/fs/GitUrlResolverTest.java
This pull request is backport  of a commit  from master https://github.com/codenvy/che-core/commit/cc010b2901f1fa30192e7528d46d2735e27d505c
=> CLDIDE-2656 : Support both http and https in git server read-only URL

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/theme/Theme.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/EditorPartStackPresenter.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/widgets/editortab/EditorTab.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/widgets/editortab/EditorTabWidget.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/widgets/editortab/EditorTabWidget.ui.xml, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/DarkTheme.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/LightTheme.java
Feature request.
If user navigates in source code by pressing F4, he can open decompiled class from jar library, so we may mark editor tab with special color to allow user understand where exactly he is.
Screencast of this functionality https://slack-files.com/T02G3VAG4-F0GTN22GZ-354488aedd
@evidolob @vparfonov @skabashnyuk
=> Mark readonly opened files with another color

platform-api/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/MachineManager.java, platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/RuntimeWorkspaceRegistry.java, platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceManager.java, platform-api/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/RuntimeWorkspaceRegistryTest.java
Implement [WorkspaceStatus](https://github.com/codenvy/che-core/blob/master/platform-api/che-core-api-core/src/main/java/org/eclipse/che/api/core/model/workspace/WorkspaceStatus.java) spec by `RuntimeWorkspaceRegistry` which basically means the following: 
* Runtime workspaces won't stack in `STARTING` state if dev-machine failed to start
* Runtime workspace won't stack in `STOPPING` state if dev-machine failed to stop
* Runtime workspace status won't be affected if any machine different from dev failed to start
* Registry returns _up to date `RuntimeWorkspace` instance_ (with already started machines)
Cover `RuntimeWorkspaceRegistry` with tests.
Fix tomcat stop behaviour, now machines are stopped in `MachineManager#cleanup()` not in `RuntimeWorkspaceRegistry`
@skabashnyuk, @garagatyi, …
=> IDEX-3612: Remove workspace from registry after workspace start error

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/action/IdeActions.java, ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/action/Presentation.java, ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/theme/Theme.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/CoreLocalizationConstant.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/ActionManagerImpl.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/StandardComponentInitializer.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/inject/CoreGinModule.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/menu/ContextMenu.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/EditorPartStackPresenter.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/EditorPartStackView.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/EditorTabContextMenu.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/EditorTabContextMenuFactory.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/actions/CloseAction.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/actions/CloseAllAction.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/actions/CloseAllExceptPinnedAction.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/actions/CloseOtherAction.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/actions/EditorAbstractAction.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/actions/PinEditorTabAction.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/actions/ReopenClosedFileAction.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/event/CloseNonPinnedEditorsEvent.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/event/PinEditorTabEvent.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/widgets/editortab/EditorTab.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/widgets/editortab/EditorTabWidget.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/widgets/editortab/EditorTabWidget.ui.xml, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/DarkTheme.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/theme/LightTheme.java, ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties, ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/part/editor/EditorPartStackPresenterTest.java, ide/che-core-ide-app/src/test/java/org/eclipse/che/ide/part/widgets/editortab/EditorTabWidgetTest.java
Context menu contains:
1. Close action - closes current selected editor.
2. Close All action - closes all opened editors.
3. Close All but Pinned action - closes all editors that don't have pin.
4. Close Other action - closes all editors but leaves current selected.
5. Reopen Closed Tab action - reopens last closed editor.
6. Pin/Unpin Editor Tab - mark/unmark current selected tab with pin.
Screencast: https://slack-files.com/T02G3VAG4-F0H1D6P47-d3213511d4
@vparfonov @evidolob @skabashnyuk wdyt?
=> Proposal to add context menu to editor tabs

ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/action/IdeActions.java, ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/recent/RecentList.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/CoreLocalizationConstant.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/ActionManagerImpl.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/StandardComponentInitializer.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/inject/CoreGinModule.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/recent/OpenRecentFileViewImpl.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/recent/OpenRecentFileViewImpl.ui.xml, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/recent/OpenRecentFilesAction.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/recent/OpenRecentFilesPresenter.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/recent/OpenRecentFilesView.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/recent/RecentFileAction.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/recent/RecentFileActionFactory.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/recent/RecentFileList.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/editor/recent/RecentFileStore.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/project/node/ItemReferenceBasedNode.java, ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties, ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/part/editor/recent/recent.css
New dialog will display list of recently opened files (file name and path).
Double clicking on file will open editor.
User may call this dialog by hotkey Ctrl+E (Linux/Windows) or Command+E (Mac)
Also new menu item: File->Recent.
Will contains the same list. Also user can clear recent list by menu item File->Recent->Clear Recent List
Screencast: https://slack-files.com/T02G3VAG4-F0H2V70HX-a2d294fdf9
@vparfonov @skabashnyuk @evidolob wdyt?
=> Proposal to add recent files functionality

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/bootstrap/FactoryWorkspaceComponent.java, platform-api-client-gwt/che-core-client-gwt-factory/pom.xml, platform-api-client-gwt/che-core-client-gwt-factory/src/main/java/org/eclipse/che/api/factory/gwt/client/FactoryServiceClient.java, platform-api-client-gwt/che-core-client-gwt-factory/src/main/java/org/eclipse/che/api/factory/gwt/client/FactoryServiceClientImpl.java, platform-api/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryService.java, platform-api/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/LinksHelper.java, platform-api/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/impl/FactoryBaseValidator.java, platform-api/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/impl/FactoryBaseValidatorTest.java
In case when we create a factory from the workspace inside ide we cannot choose factory image without ugly workarounds, it was proposed to add a method that consumes factory dto instance without images.
=> CLDIDE-2648: Implement save factory without image

platform-api/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/proxy/MachineExtensionProxyServlet.java, platform-api/che-core-api-machine/src/test/java/org/eclipse/che/api/machine/server/proxy/MachineExtensionProxyServletTest.java
error 404 changed into 503 if machine not here (service unavailable)
error 500 changed into 502 if there is error when communicating (bad gateway)
Change-Id: I0853af71062d7c102a8015c16c8f61097a9f8d2e
=> IDEX-3854 Update error code returned if there is an error in ServletProxy

commons/che-core-commons-gwt/src/main/java/org/eclipse/che/security/oauth/JsOAuthWindow.java
$wnd.IDE.config is a deprecated variable and it returns empty workspace name, so I check that loaded page url is equels to given url.
@vparfonov @skabashnyuk
=> IDEX-3842: Fix GitHub Authorize application

platform-api/che-core-api-workspace/pom.xml, platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java
we need it in property becouse context can be fifferent depend on packaging for example in Che it will be 'ide' but in hosted - 'ws'
=> Add special property for IDE url context

platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitProjectType.java, platform-api/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitValueProviderFactory.java
@vparfonov @skabashnyuk @sleshchenko please review
=> IDEX-3576: Add git remote and branch to projects attributes

ide/che-core-ide-generators/src/main/java/org/eclipse/che/util/DtoFactoryVisitorRegistryGenerator.java, ide/che-core-ide-generators/src/main/java/org/eclipse/che/util/ExtensionManagerGenerator.java, ide/che-core-ide-generators/src/main/java/org/eclipse/che/util/IDEInjectorGenerator.java, ide/che-core-ide-generators/src/main/java/org/eclipse/che/util/IgnoreUnExistedResourcesReflectionConfigurationBuilder.java
Created reflections configuration builder that ignore resources that is not exists.
It happens when ide generators runs on generate-sources stage and ../target/classes folder is listed in class path but not exists.
Reflections print NPE for such folders. See more https://github.com/ronmamo/reflections/issues/111
=> IDEX-4101 Ignore not existing resources in class path during scanning classes

platform-api/pom.xml, pom.xml
Removed unused property **maven.model.version** in pom.xml since we don't use **org.apache.maven.maven-model** anymore
@vparfonov
=> Remove unused property maven.model.version in pom.xml since we don't use org.apache.maven.maven-model anymore

ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/CoreLocalizationConstant.java, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/actions/RenameItemAction.java, ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties, ide/che-core-ide-ui/src/main/java/org/eclipse/che/ide/ui/dialogs/input/InputDialogPresenter.java
1. Do not display error when new name equals current name at renaming item
2. Disable button "OK" in this case
3. Display current name in the title of the rename dialog.
=> IDEX-4127. Do not display error when new name equals current name at renaming item

ide/che-core-ide-app/pom.xml, ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/Resources.java
* Updated license header for org.eclipse.che.ide.Resources
* Removed unnecessary excludes in configuration of license-maven-plugin
@vparfonov
=> Update license header; remove unnecessary excludes in configuration of license-maven-plugin

platform-api/che-core-api-infrastructure-local/src/main/java/org/eclipse/che/api/local/LocalWorkspaceDaoImpl.java
This will allow don't use the same workspace object at the same time while different operations are executed.
=> IDEX-4157. Use copy workspace object at operations with this one

platform-api/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/WsAgentLauncherImpl.java, platform-api/che-core-api-machine/src/test/java/org/eclipse/che/api/machine/server/WsAgentLauncherImplTest.java, platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/DefaultWorkspaceConfigValidator.java, platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceConfigValidator.java, platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceManager.java, platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/UsersWorkspaceImpl.java, platform-api/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/DefaultWorkspaceConfigValidatorTest.java, platform-api/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceManagerTest.java
Leave the only one `validate(WorkspaceConfig)` method in the `WorkspaceConfigValidator`, move default implementation from the `model.impl` package.
@skabashnyuk, @akorneta, @garagatyi  please review
=> CLDIDE-2692: Clean up workspace config validator

platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/DefaultProjectManager.java, platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/Project.java, platform-api/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/ProjectTest.java
Current code perform a simple text comparison to check if the module being conflicts with an existing module. Fixed this by comparing actual Path objects.
Current code does not update the modules list if a non-project parent folder of the module is renamed - it explicit requires the renamed folder to be a project folder in order to perform any module updates. Fixed.
Current code does not update projects other than the project that contains the module folder - it only cuts the renamed folder's path and checks that the enclosing project has the renamed folder listed as a module. Fixed.
=> Extended support for module paths

platform-api/che-core-api-dto/src/main/java/org/eclipse/che/dto/server/DtoFactory.java
avoid an unnecessary double serialization if a JsonElement is availableand a DTO needs to be created from it.
=> Allow creating a DTO from JsonElement directly
